# Generated by Django 5.2.8 on 2025-12-18 11:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('completed_morning', models.BooleanField(default=False, verbose_name='Утренний блок заполнен')),
                ('completed_evening', models.BooleanField(default=False, verbose_name='Вечерний блок заполнен')),
                ('mood', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Настроение (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дневная запись',
                'verbose_name_plural': 'Дневные записи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NudgePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст фразы')),
                ('category', models.CharField(choices=[('streak', 'Сохранить стрик'), ('comeback', 'Вернуться после перерыва')], db_index=True, default='streak', max_length=32, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Фраза напоминания',
                'verbose_name_plural': 'Фразы напоминаний',
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Внутренний идентификатор, по которому бот понимает, какой это вопрос.', max_length=50, unique=True, verbose_name='Код вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('period', models.CharField(choices=[('morning', 'Утро'), ('evening', 'Вечер'), ('weekly', 'Недельный вопрос')], db_index=True, default='evening', max_length=20, verbose_name='Период')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Определяет порядок вопросов утром/вечером.', verbose_name='Порядок в блоке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон вопроса',
                'verbose_name_plural': 'Шаблоны вопросов',
                'ordering': ['period', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации в боте')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать пользователям')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Задание недели',
                'verbose_name_plural': 'Задания недели',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса в момент ответа')),
                ('answer_text', models.TextField(verbose_name='Ответ пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время ответа')),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.dailyentry', verbose_name='Дневная запись')),
                ('question', models.ForeignKey(blank=True, help_text='Может быть null, если вопрос потом удалили или изменили.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='core.questiontemplate', verbose_name='Шаблон вопроса')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreakState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущий стрик (в днях)')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Лучший стрик (в днях)')),
                ('last_completed_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата последнего полностью заполненного дня')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_state', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стрик пользователя',
                'verbose_name_plural': 'Стрики пользователей',
            },
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='core.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Moscow', help_text='Строка часового пояса, например Europe/Moscow или Europe/Athens.', max_length=64, verbose_name='Часовой пояс')),
                ('morning_enabled', models.BooleanField(default=True, verbose_name='Утренние вопросы включены')),
                ('evening_enabled', models.BooleanField(default=True, verbose_name='Вечерние вопросы включены')),
                ('morning_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Время утреннего напоминания')),
                ('evening_time', models.TimeField(default=datetime.time(21, 0), verbose_name='Время вечернего напоминания')),
                ('week_start', models.IntegerField(default=1, help_text='1 = Понедельник, 7 = Воскресенье (ISO).', verbose_name='День начала недели')),
                ('notify_missed_days', models.BooleanField(default=True, verbose_name='Напоминать о пропусках')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.telegramuser', verbose_name='Пользователь')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together={('user', 'date')},
        ),
        migrations.CreateModel(
            name='WeeklyCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='Начало недели')),
                ('week_end', models.DateField(db_index=True, verbose_name='Конец недели')),
                ('mid_reflection', models.TextField(blank=True, verbose_name='Промежуточный итог')),
                ('final_reflection', models.TextField(blank=True, verbose_name='Итог недели')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Неделя завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_cycles', to='core.telegramuser', verbose_name='Пользователь')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cycles', to='core.weeklytask', verbose_name='Задание недели')),
            ],
            options={
                'verbose_name': 'Недельный цикл',
                'verbose_name_plural': 'Недельные циклы',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
