# Generated by Django 5.2.8 on 2025-12-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='iso_week',
            field=models.IntegerField(db_index=True, default=2001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklytask',
            name='iso_year',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='weeklytask',
            unique_together={('iso_year', 'iso_week')},
        ),
    ]
