# Generated by Django 5.2.8 on 2026-01-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weeklytask_iso_week_weeklytask_iso_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='skipped',
            field=models.BooleanField(default=False, verbose_name='День пропущен'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда пропущен'),
        ),
    ]
